sudo: required
language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

env:
  - CC=gcc
  - CC=clang

matrix:
  allow_failures:
    - php: nightly
      env:  CC=gcc
    - php: nightly
      env:  CC=clang

#
addons:
  apt:
    packages: clang

#
before_install:
  # phpredis
  - git clone --recursive https://github.com/phpredis/phpredis
  - cd phpredis
  - phpize
  - pecl install igbinary
  - ./configure --enable-redis-igbinary --enable-redis-lzf CFLAGS=-Wall
  - make install
  - cd ..
install:
  # some latest package cannot run on PHP5
  - composer install

before_script:
  - gem install redis
  - mkdir -p tests/nodes/ && echo > tests/nodes/nodemap
  - for PORT in $(seq 6379 6382); do redis-server --port $PORT --daemonize yes; done
  - for PORT in $(seq 7000 7011); do redis-server --port $PORT --cluster-enabled yes --cluster-config-file $PORT.conf --daemonize yes; echo 127.0.0.1:$PORT >> tests/nodes/nodemap; done
  - redis-cli --cluster create 127.0.0.1:7000 127.0.0.1:7001 127.0.0.1:7002 127.0.0.1:7003 127.0.0.1:7004 127.0.0.1:7005 127.0.0.1:7006 127.0.0.1:7007 127.0.0.1:7008 127.0.0.1:7009 127.0.0.1:7010 127.0.0.1:7011 --cluster-replicas 3
  - echo 'extension = redis.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
script:
  - composer test:unit
